project 'IrisProject001.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IrisProject001' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IrisProject001

  target 'IrisProject001Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IrisProject001UITests' do
    inherit! :search_paths
    # Pods for testing
  end
  

end
